# Generated by Django 4.2 on 2023-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerName', models.CharField(max_length=255)),
                ('SerDisc', models.TextField()),
                ('SerImg', models.ImageField(upload_to='Service_images/')),
            ],
        ),
    ]
